// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneNumberChecker.Data.Access;

#nullable disable

namespace PhoneNumberChecker.Data.Access.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231117061309_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhoneNumberChecker.Data.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df62ad04-776c-4bce-846d-cc7cd0c0aeb3"),
                            CountryCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("f4bd356e-cfc3-4119-9428-474c11056fd5"),
                            CountryCode = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("e82c01ae-251b-4b2b-a006-63ff32968790"),
                            CountryCode = "IT",
                            Name = "Italy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
